import { ArrowDownRight, ArrowUpRight, BarChart3, Lightbulb } from 'lucide-react';
import { useMemo } from 'react';
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getExpenses } from '../services/storage';
import { formatCurrency } from '../utils/formatters';

const colors = ['#38bdf8', '#34d399', '#fbbf24', '#fb7185', '#a78bfa', '#f97316', '#22d3ee', '#94a3b8'];

function Insights() {
  const expenses = getExpenses();
  const categoryData = useMemo(() => Object.entries(expenses.reduce<Record<string, number>>((totals, expense) => { totals[expense.category] = (totals[expense.category] || 0) + expense.amount; return totals; }, {})).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value), [expenses]);
  const personData = useMemo(() => Object.entries(expenses.reduce<Record<string, number>>((totals, expense) => { totals[expense.paidBy] = (totals[expense.paidBy] || 0) + expense.amount; return totals; }, {})).map(([name, value]) => ({ name: name === 'janhavi' ? 'Janhavi' : name === 'aditya' ? 'Aditya' : 'Shared', value })), [expenses]);
  const total = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const topCategory = categoryData[0];
  const sharedTotal = expenses.filter((expense) => expense.type === 'shared').reduce((sum, expense) => sum + expense.amount, 0);
  const personalTotal = total - sharedTotal;

  return (
    <div className="space-y-6">
      <header><p className="text-sm font-medium uppercase tracking-[0.18em] text-violet-300">See the shape of it</p><h1 className="mt-2 text-3xl font-semibold text-white">Insights</h1><p className="mt-2 text-sm text-slate-400">A clearer read on where your shared life is going.</p></header>
      <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-[24px] border border-white/10 bg-slate-900/80 p-4"><div className="text-xs uppercase tracking-[0.16em] text-slate-400">Total tracked</div><div className="mt-2 text-2xl font-semibold text-white">{formatCurrency(total)}</div><div className="mt-2 flex items-center gap-1 text-xs text-emerald-300"><ArrowUpRight size={14} /> Across {expenses.length} expenses</div></div><div className="rounded-[24px] border border-white/10 bg-slate-900/80 p-4"><div className="text-xs uppercase tracking-[0.16em] text-slate-400">Shared spending</div><div className="mt-2 text-2xl font-semibold text-white">{formatCurrency(sharedTotal)}</div><div className="mt-2 text-xs text-slate-400">{total ? Math.round((sharedTotal / total) * 100) : 0}% of tracked spend</div></div><div className="rounded-[24px] border border-white/10 bg-slate-900/80 p-4"><div className="text-xs uppercase tracking-[0.16em] text-slate-400">Personal spending</div><div className="mt-2 text-2xl font-semibold text-white">{formatCurrency(personalTotal)}</div><div className="mt-2 flex items-center gap-1 text-xs text-amber-300"><ArrowDownRight size={14} /> Keep a little context</div></div></section>
      <section className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><div className="rounded-[28px] border border-white/10 bg-slate-900/80 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-white">Spending by category</h2><p className="mt-1 text-xs text-slate-400">September 2026</p></div><BarChart3 size={20} className="text-sky-300" /></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={categoryData} layout="vertical" margin={{ left: 8, right: 12 }}><XAxis type="number" hide /><YAxis dataKey="name" type="category" width={92} tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: 'rgba(255,255,255,0.04)' }} formatter={(value) => formatCurrency(Number(value))} contentStyle={{ background: '#0f172a', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 12 }} /><Bar dataKey="value" radius={[0, 6, 6, 0]}>{categoryData.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}</Bar></BarChart></ResponsiveContainer></div></div><div className="rounded-[28px] border border-white/10 bg-slate-900/80 p-5"><h2 className="font-semibold text-white">Who paid?</h2><p className="mt-1 text-xs text-slate-400">The current balance of effort</p><div className="h-56"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={personData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={78} paddingAngle={4}>{personData.map((entry, index) => <Cell key={entry.name} fill={colors[index + 1]} />)}</Pie><Tooltip formatter={(value) => formatCurrency(Number(value))} contentStyle={{ background: '#0f172a', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 12 }} /></PieChart></ResponsiveContainer></div><div className="space-y-2">{personData.map((item, index) => <div key={item.name} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-slate-300"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: colors[index + 1] }} />{item.name}</span><span className="font-medium text-white">{formatCurrency(item.value)}</span></div>)}</div></div></section>
      <section className="flex items-start gap-3 rounded-[24px] border border-violet-400/20 bg-violet-400/10 p-4"><Lightbulb size={20} className="mt-0.5 shrink-0 text-violet-200" /><div><h2 className="font-medium text-white">A small pattern</h2><p className="mt-1 text-sm text-violet-100/75">{topCategory ? `${topCategory.name} is your largest category at ${formatCurrency(topCategory.value)}. A quick check-in here could make the biggest difference this month.` : 'Add a few expenses to see a useful pattern here.'}</p></div></section>
    </div>
  );
}

export default Insights;
